clockd: logging.c File Reference
logging.c File Reference
clockd logging stuff (see logging.h)
#include "logging.h"
#include "internal_time_utils.h"
#include <stdio.h>
Functions
void dump_date (const char *server_tz)
void log_tm (const char *tag, const struct tm *tm)
Detailed Description
Copyright (C) 2008 Nokia. All rights reserved.
Author:
Simo Piiroinen <simo.piiroinen@nokia.com>
Raimo Vuonnala <raimo.vuonnala@nokia.com>
Function Documentation
void dump_date (const char * server_tz)
Dump current date settings to syslog.
Parameters:
server_tz current server timezone to be printed in log
Referenced by handle_csd_net_time_change(), server_init(), server_set_time_cb(), and server_set_tz_cb().
void log_tm (const char * tag, const struct tm * tm)
Log tm structure
Parameters:
tag string describing tm
tm tm to be logged
Referenced by handle_csd_net_time_change(), and mcc_tz_find_tz_in_country_tz_list().